title: "Sai Kiran Mayakuntla"
description: "(సాయి కిరణ్ మాయకుంట్ల)"
theme: jekyll-theme-merlot
baseurl: "" # Leave this empty unless your site is in a subdirectory
url: "https://saikiran92.github.io" # Update this with your GitHub Pages URL

# Navigation links
header_pages:
  - index.md
  - blog.md
  - projects.md

# Social media links
social:
  github: https://github.com/saikiran92
  linkedin: https://www.linkedin.com/in/saikiranm92
