title: "Sai Kiran Mayakuntla"
description: "Finance Professional. Puzzle Enthusiast. Avid Reader."
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: "" # Leave this empty unless your site is in a subdirectory
url: "https://saikiran92.github.io" # Update this with your GitHub Pages URL

nav:
  - home: /
  - blog: /blog/
  - projects: /projects/
  - about: /about/

# Social media links
social:
  github: https://github.com/saikiran92
  linkedin: https://www.linkedin.com/in/saikiranm92
